name: Python package
on: [push]

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: abatilo/actions-poetry@v1.1.0
      with:
        python_version: 3.8.0
        poetry_version: 1.0.0
        args: install
    - name: Run flake8
      uses: abatilo/actions-poetry@v1.1.0
      with:
        python_version: 3.8.0
        poetry_version: 0.12.17
        args: run python -m flake8 src/ 
    - name: Run pytest
      uses: abatilo/actions-poetry@v1.1.0
      with:
        python_version: 3.8.0
        poetry_version: 0.12.17
        args: run python -m pytest --cov=src --cov-branch --cov-fail-under=100 tests/
